In [1]:
!pip install numpy==1.15.1

Collecting numpy==1.15.1
  Downloading https://files.pythonhosted.org/packages/fe/94/7049fed8373c52839c8cde619acaf2c9b83082b935e5aa8c0fa27a4a8bcc/numpy-1.15.1-cp36-cp36m-manylinux1_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 3.5MB/s eta 0:00:011
Installing collected packages: numpy
  Found existing installation: numpy 1.14.3
    Uninstalling numpy-1.14.3:
      Successfully uninstalled numpy-1.14.3
Successfully installed numpy-1.15.1
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [2]:
!pip install pyarrow==0.15.1

Collecting pyarrow==0.15.1
  Downloading https://files.pythonhosted.org/packages/dd/77/5865b367a6792da2f811ae49391c1f85c29b29663555aac0a118fe8e153e/pyarrow-0.15.1-cp36-cp36m-manylinux1_x86_64.whl (59.0MB)
    100% |████████████████████████████████| 59.0MB 864kB/s  eta 0:00:01
Requirement already satisfied: six>=1.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pyarrow==0.15.1) (1.11.0)
Requirement already satisfied: numpy>=1.14 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pyarrow==0.15.1) (1.15.1)
Installing collected packages: pyarrow
Successfully installed pyarrow-0.15.1
You are using pip version 10.0.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [3]:
import pandas as pd
import pyarrow

In [15]:
pd.set_option('display.max_columns', None)

In [4]:
data = pd.read_csv('atc_listings.csv')

In [16]:
data.head()

,CAR_ID,CUSTOMER_ID,STOCK_ID,VIN,MAKE,MODEL,MODEL_YEAR,TRIM_NAME,BODYSTYLE,NEW_IND,CERTIFIED_IND,PRICE_NUM,MSRP_NUM,MILEAGE_NUM,SPOTLIGHT_IND,REDUCED_IND,SPECIAL_CNT,INCENTIVE_PRICE,PAYMENT_OFFERS_IND,MAIN_LISTING_IMAGE_URL,SOURCE_CREATED_DATETIME,SOURCE_MODIFIED_DATETIME,DELETE_RECORD_IND,OEM_COLOR,COLOR,INT_COLOR,DOORS,ENGINE_TYPE,FUEL_TYPE,DRIVE_TYPE,TRANSMISSION_TYPE
0,485750148,70042,P25088,1LN6L9RP0J5606615,Lincoln,Continental,2018,Reserve,Sedan,0,1,60935,0,5182,0,0,0,0,0,https://dealers-admin.autotrader.com/dc/images...,2019-08-07,2019-08-27,1,WHITE PLATINUM METALLIC TRI-CO,WHITE,BROWN,Four Door,6-Cylinder Turbo,Gasoline,2 Wheel Drive - Front,AUTOMATIC
1,492720575,83813,37230,JTJYARBZXK2125964,Lexus,NX 300,2019,FWD,Sport Utility,1,0,40133,44733,30,0,0,0,0,0,https://dealers-admin.autotrader.com/dc/images...,2019-09-17,2019-09-30,1,CAVIAR,UNAVAIL,OFFWHITE,Four Door,4-Cylinder Turbo,Gasoline,2 Wheel Drive - Front,AUTOMATIC
2,472773630,67878603,P2510,JN1BJ1CP3HW025765,Nissan,Rogue Sport,2017,SL,Sport Utility,0,0,22995,0,8,0,0,0,0,0,https://dealers-admin.autotrader.com/dc/images...,2019-08-23,2019-09-05,1,MAGNETIC BLACK,BLACK,CHARCOAL,Four Door,4-Cylinder,Gasoline,2 Wheel Drive - Front,AUTOMATIC
3,472773630,72394791,P2510,JN1BJ1CP3HW025765,Nissan,Rogue Sport,2017,SL,Sport Utility,0,1,20700,0,8,0,0,0,0,0,https://dealers-admin.autotrader.com/dc/images...,2019-08-23,2019-12-27,1,MAGNETIC BLACK,BLACK,CHARCOAL,Four Door,4-Cylinder,Gasoline,2 Wheel Drive - Front,AUTOMATIC
4,483058027,1359774,18-722,WMWXM5C5XF3A04636,MINI,Cooper,2015,2-Door Hardtop,Hatchback,0,0,12990,0,18156,0,0,0,0,0,https://dealers-admin.autotrader.com/dc/images...,2019-10-29,2019-10-29,1,GREEN,GREEN,BLACK,Two Door,3-Cylinder Turbo,Gasoline,2 Wheel Drive - Front,MANUAL

In [6]:
print (data.shape)
data.columns

(9215447, 31)

Index(['CAR_ID', 'CUSTOMER_ID', 'STOCK_ID', 'VIN', 'MAKE', 'MODEL',
       'MODEL_YEAR', 'TRIM_NAME', 'BODYSTYLE', 'NEW_IND', 'CERTIFIED_IND',
       'PRICE_NUM', 'MSRP_NUM', 'MILEAGE_NUM', 'SPOTLIGHT_IND', 'REDUCED_IND',
       'SPECIAL_CNT', 'INCENTIVE_PRICE', 'PAYMENT_OFFERS_IND',
       'MAIN_LISTING_IMAGE_URL', 'SOURCE_CREATED_DATETIME',
       'SOURCE_MODIFIED_DATETIME', 'DELETE_RECORD_IND', 'OEM_COLOR', 'COLOR',
       'INT_COLOR', 'DOORS', 'ENGINE_TYPE', 'FUEL_TYPE', 'DRIVE_TYPE',
       'TRANSMISSION_TYPE'],
      dtype='object')

In [7]:
data['VIN'].str.len().unique()

array([17., nan])

In [8]:
max(data['SOURCE_CREATED_DATETIME'])

'2019-10-31'

In [9]:
min(data['SOURCE_CREATED_DATETIME'])

'2019-08-01'

In [11]:
data.describe()

,CAR_ID,CUSTOMER_ID,MODEL_YEAR,NEW_IND,CERTIFIED_IND,PRICE_NUM,MSRP_NUM,MILEAGE_NUM,SPOTLIGHT_IND,REDUCED_IND,SPECIAL_CNT,INCENTIVE_PRICE,PAYMENT_OFFERS_IND,DELETE_RECORD_IND
count,9.215447e+06,9.215447e+06,9.215447e+06,9.215447e+06,9.215447e+06,9.215447e+06,9.215447e+06,9.215447e+06,9.215447e+06,9.215447e+06,9.215447e+06,9.215447e+06,9215447.0,9.215447e+06
mean,5.281874e+08,4.497355e+07,2.016485e+03,3.334226e-01,6.588970e-02,2.471761e+04,1.233749e+04,3.375684e+04,8.677278e-02,9.294243e-02,3.811784e-01,1.309052e+03,0.0,9.034988e-01
std,3.940181e+06,3.431491e+07,3.750016e+00,4.714361e-01,2.480892e-01,1.762486e+04,2.091117e+04,4.294142e+04,2.815018e-01,2.903518e-01,9.823492e-01,7.178007e+03,0.0,2.952774e-01
min,2.040499e+08,6.634400e+04,1.981000e+03,0.000000e+00,0.000000e+00,0.000000e+00,-2.550000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00
25%,5.259472e+08,6.148540e+05,2.015000e+03,0.000000e+00,0.000000e+00,1.440000e+04,0.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.000000e+00
50%,5.284461e+08,6.701597e+07,2.018000e+03,0.000000e+00,0.000000e+00,2.290000e+04,0.000000e+00,2.154800e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.000000e+00
75%,5.309549e+08,7.145244e+07,2.019000e+03,1.000000e+00,0.000000e+00,3.298000e+04,2.654500e+04,4.673000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,1.000000e+00
max,5.335678e+08,1.000527e+08,2.020000e+03,1.000000e+00,1.000000e+00,9.999999e+06,6.305000e+05,8.946640e+05,1.000000e+00,1.000000e+00,1.200000e+01,5.247350e+05,0.0,1.000000e+00

In [10]:
data.isna().sum()

CAR_ID                          0
CUSTOMER_ID                     0
STOCK_ID                    93026
VIN                            29
MAKE                            0
MODEL                           0
MODEL_YEAR                      0
TRIM_NAME                       0
BODYSTYLE                       0
NEW_IND                         0
CERTIFIED_IND                   0
PRICE_NUM                       0
MSRP_NUM                        0
MILEAGE_NUM                     0
SPOTLIGHT_IND                   0
REDUCED_IND                     0
SPECIAL_CNT                     0
INCENTIVE_PRICE                 0
PAYMENT_OFFERS_IND              0
MAIN_LISTING_IMAGE_URL          0
SOURCE_CREATED_DATETIME         0
SOURCE_MODIFIED_DATETIME        0
DELETE_RECORD_IND               0
OEM_COLOR                     149
COLOR                           1
INT_COLOR                       0
DOORS                           0
ENGINE_TYPE                     0
FUEL_TYPE                       0
DRIVE_TYPE                      0
TRANSMISSION_TYPE               0
dtype: int64