In [1]:
import pandas as pd

In [2]:
vma = pd.read_csv('vma.csv')

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
vma.head()

,Key,Source,Vin,Year,Make,Model,Trim,Mileage,Date,MIDMapAlgorithm,mid15,VPID,MMR_adj_current,RMI_adj_current,AvgPrice,avgmiles,Velocity,Salesefficiency,AvgDaysToSell,vol_tier,availability,inventory,spread_current
0,5004514,wholesale,1FTEW1EF7GFD46982,2016,Ford,F-150,Lariat,36524.0,2019-08-08,Exact,2.016018e+14,2016_Ford_F-150,30800.0,33600.0,26395.0,45682.0,Cold,0.533909,22.0,Tier1,Medium,1582.0,2800.0
1,5092247,wholesale,1FMCU0JD7HUB06187,2017,Ford,Escape,Titanium,20970.0,2019-08-01,Exact,2.017018e+14,2017_Ford_Escape,15900.0,18600.0,14428.0,33843.0,Hot,0.825581,19.0,Tier1,Medium,2286.0,2700.0
2,5092247,wholesale,1FMCU0J98GUC56903,2016,Ford,Escape,Titanium,19531.0,2019-08-01,Exact,2.016018e+14,2016_Ford_Escape,15750.0,17950.0,13638.0,41953.0,Hot,0.776985,18.0,Tier1,Low,323.0,2200.0
3,5420499,wholesale,1FADP3FE9HL274413,2017,Ford,Focus,SE,36482.0,2019-08-01,Exact,2.017018e+14,2017_Ford_Focus,9125.0,10950.0,10469.0,36473.0,Hot,0.702541,24.0,Tier1,High,463.0,1825.0
4,5177158,wholesale,1FT8W3DTXHEC60427,2017,Ford,F-350,Lariat,109622.0,2019-08-01,Exact,2.017018e+14,2017_Ford_Super Duty F-350 DRW,39500.0,43200.0,45758.0,60619.0,Hot,0.491837,19.0,Tier4,High,120.0,3700.0

In [23]:
Wholesale = pd.read_csv("Wholesale.csv")
pd.set_option('display.max_columns', None)
Wholesale.head()

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,AUC_AUCTION_CD,BUYER_UID,SELLER_UID,VIN,MID,UNIT_TYPE_DESC,MODEL_YR,MAKE_DESC,MODEL_DESC,TRIM_DESC,BODY_DESC,EXTERIOR_COLOR_DESC,ODOMETER,FINAL_CR_GRADE,CR_FLG,FINAL_PUR_AMT,AT_SALE_NAT_MMR,SOLD_DT_KEY,BUYER_HOW_PAID_CD,FLOORPLAN_CUST_OVC_ID,FLOORPLAN_CUST_CUR_CUST_NM,FLOORPLAN_UID
0,MAA,5004514,4910256,1FTEW1EF7GFD46982,201601757045540,Truck,2016,Ford,F-150,Lariat,Truck,Gray,36524.0,4.1,1,33800.0,33700.0,20190808,Floored,NaN,NaN,NaN
1,NASH,5092247,4910256,1FMCU0JD7HUB06187,201701756938959,SUV,2017,Ford,Escape,Titanium,SUV,Silver,20970.0,4.6,1,18200.0,17700.0,20190801,Floored,NaN,NaN,NaN
2,NASH,5092247,4910256,1FMCU0J98GUC56903,201601756930838,SUV,2016,Ford,Escape,Titanium,SUV,White,19531.0,4.6,1,17900.0,17000.0,20190801,Floored,NaN,NaN,NaN
3,MISS,5420499,4910256,1FADP3FE9HL274413,201701772320086,Car,2017,Ford,Focus,SE,Sedan,Silver,36482.0,2.9,1,7900.0,10000.0,20190801,Floored,6048260.0,NEXT GEAR CAPITAL - FLOORPLAN,12000100.0
4,MISS,5177158,4910256,1FT8W3DTXHEC60427,201701755783113,Truck,2017,Ford,F-350,Lariat,Truck,Black,109622.0,3.3,1,40800.0,42000.0,20190801,Floored,6048252.0,ALLY FINANCIAL - FLOORPLAN,12000078.0

In [24]:
Wholesale.shape

(1191471, 22)

In [25]:
client_master = pd.read_csv("client_master.csv")

In [26]:
client_master.head()

,acctnum,accttype,acctsubtype,caid,custname,custcity,custaddrline1,custprovincecode,custpostalcode,externalidtype,externalid,acctaddline1,acctcity,acctprovincecd,acctpostalcd
0,DETA7000403,OVC,AUCTION,CA11741570,GARY L HAZELLIEF/PUBLIC,ANN ARBOR,3085 WHISPERWOOD DR,USA-MI,48105,OVC ID,5698281,3085 WHISPERWOOD DR,ANN ARBOR,USA-MI,48105
1,AREN7000438,OVC,AUCTION,CA11740438,ARSALAN ALI,VILLA PARK,901 W NORTH AVE,USA-IL,60181,OVC ID,5700002,901 W NORTH AVE,VILLA PARK,USA-IL,60181
2,ALOH7001395,OVC,AUCTION,CA11747260,GARY OSHIRO,HONOLULU,3720 MAHINA AVE,USA-HI,96816,OVC ID,5740421,3720 MAHINA AVE,HONOLULU,USA-HI,96816
3,80506,NGC,DEALER,CA11346933,BAVARIAN MOTORS,TOMBALL,9428 HUFSMITH RD,USA-TX,77375,NGC AA,5317162,8561 RAYSON RD STE C,HOUSTON,USA-TX,77080
4,5224772,OVC,AUCTION,CA11465278,JETT AUCTION LIMITED,PARKSVILLE,861 ALLSBROOK RD,CAN-BC,V9P 2A9,OVC ID,399669,861 ALLSBROOK RD,PARKSVILLE,CAN-BC,V9P 2A9

In [8]:
client_master.acctnum.unique()

array(['DETA7000403', 'AREN7000438', 'ALOH7001395', ..., 'SSAA7000574',
       'MASC0372438', '4940663'], dtype=object)

In [27]:
wholesale_match = client_master[client_master['accttype']=='OVC']
wholesale_match = wholesale_match[wholesale_match['acctsubtype']=='AUCTION']

In [28]:
wholesale_match = wholesale_match.loc[:,['acctnum','caid']]

In [29]:
wholesale_match.shape

(578001, 2)

In [30]:
len(Wholesale.BUYER_UID.unique())

54882

In [31]:
wholesale_match = pd.merge(Wholesale, wholesale_match.drop_duplicates(subset=['acctnum']), left_on='BUYER_UID', right_on='acctnum',how='left')

In [32]:
wholesale_match.shape

(1191471, 24)

In [33]:
vma_wholesale= vma[0:1191471]

In [34]:
vma_wholesale.head()

,Key,Source,Vin,Year,Make,Model,Trim,Mileage,Date,MIDMapAlgorithm,mid15,VPID,MMR_adj_current,RMI_adj_current,AvgPrice,avgmiles,Velocity,Salesefficiency,AvgDaysToSell,vol_tier,availability,inventory,spread_current
0,5004514,wholesale,1FTEW1EF7GFD46982,2016,Ford,F-150,Lariat,36524.0,2019-08-08,Exact,2.016018e+14,2016_Ford_F-150,30800.0,33600.0,26395.0,45682.0,Cold,0.533909,22.0,Tier1,Medium,1582.0,2800.0
1,5092247,wholesale,1FMCU0JD7HUB06187,2017,Ford,Escape,Titanium,20970.0,2019-08-01,Exact,2.017018e+14,2017_Ford_Escape,15900.0,18600.0,14428.0,33843.0,Hot,0.825581,19.0,Tier1,Medium,2286.0,2700.0
2,5092247,wholesale,1FMCU0J98GUC56903,2016,Ford,Escape,Titanium,19531.0,2019-08-01,Exact,2.016018e+14,2016_Ford_Escape,15750.0,17950.0,13638.0,41953.0,Hot,0.776985,18.0,Tier1,Low,323.0,2200.0
3,5420499,wholesale,1FADP3FE9HL274413,2017,Ford,Focus,SE,36482.0,2019-08-01,Exact,2.017018e+14,2017_Ford_Focus,9125.0,10950.0,10469.0,36473.0,Hot,0.702541,24.0,Tier1,High,463.0,1825.0
4,5177158,wholesale,1FT8W3DTXHEC60427,2017,Ford,F-350,Lariat,109622.0,2019-08-01,Exact,2.017018e+14,2017_Ford_Super Duty F-350 DRW,39500.0,43200.0,45758.0,60619.0,Hot,0.491837,19.0,Tier4,High,120.0,3700.0

In [35]:
a = wholesale_match.loc[:,['caid']]
c = wholesale_match.loc[:,['FINAL_PUR_AMT','BUYER_HOW_PAID_CD','FLOORPLAN_CUST_OVC_ID','FLOORPLAN_CUST_CUR_CUST_NM','BUYER_UID']]

In [36]:
b = vma_wholesale.iloc[:,2:23]

In [37]:
wholesale_321 = pd.concat([a,b,c], axis=1)

In [38]:
wholesale_321.head()

,caid,Vin,Year,Make,Model,Trim,Mileage,Date,MIDMapAlgorithm,mid15,VPID,MMR_adj_current,RMI_adj_current,AvgPrice,avgmiles,Velocity,Salesefficiency,AvgDaysToSell,vol_tier,availability,inventory,spread_current,FINAL_PUR_AMT,BUYER_HOW_PAID_CD,FLOORPLAN_CUST_OVC_ID,FLOORPLAN_CUST_CUR_CUST_NM,BUYER_UID
0,CA11273590,1FTEW1EF7GFD46982,2016,Ford,F-150,Lariat,36524.0,2019-08-08,Exact,2.016018e+14,2016_Ford_F-150,30800.0,33600.0,26395.0,45682.0,Cold,0.533909,22.0,Tier1,Medium,1582.0,2800.0,33800.0,Floored,NaN,NaN,5004514
1,CA11266817,1FMCU0JD7HUB06187,2017,Ford,Escape,Titanium,20970.0,2019-08-01,Exact,2.017018e+14,2017_Ford_Escape,15900.0,18600.0,14428.0,33843.0,Hot,0.825581,19.0,Tier1,Medium,2286.0,2700.0,18200.0,Floored,NaN,NaN,5092247
2,CA11266817,1FMCU0J98GUC56903,2016,Ford,Escape,Titanium,19531.0,2019-08-01,Exact,2.016018e+14,2016_Ford_Escape,15750.0,17950.0,13638.0,41953.0,Hot,0.776985,18.0,Tier1,Low,323.0,2200.0,17900.0,Floored,NaN,NaN,5092247
3,CA11898930,1FADP3FE9HL274413,2017,Ford,Focus,SE,36482.0,2019-08-01,Exact,2.017018e+14,2017_Ford_Focus,9125.0,10950.0,10469.0,36473.0,Hot,0.702541,24.0,Tier1,High,463.0,1825.0,7900.0,Floored,6048260.0,NEXT GEAR CAPITAL - FLOORPLAN,5420499
4,CA11207276,1FT8W3DTXHEC60427,2017,Ford,F-350,Lariat,109622.0,2019-08-01,Exact,2.017018e+14,2017_Ford_Super Duty F-350 DRW,39500.0,43200.0,45758.0,60619.0,Hot,0.491837,19.0,Tier4,High,120.0,3700.0,40800.0,Floored,6048252.0,ALLY FINANCIAL - FLOORPLAN,5177158

In [39]:
wholesale_321 = wholesale_321.sort_values(by=['caid'])

In [41]:
wholesale_321.to_csv('wholesale_321.csv')

In [42]:
wholesale_321.shape

(1191471, 27)

In [9]:
ddc_listings = pd.read_csv('ddc_listings.csv')

In [10]:
ddc_listings.head()

,svoc_id,isFD,dealercode,domain,vin,vehiclemake,vehiclemodel,vehiclemodelyear,vehicletypestring,vehiclebodystyle,chromestyleid,mpgcity,mpghighway,odometermiles,vehicleid,vehiclestocknumber,price,first_seen_datetime,last_seen_datetime
0,70705895.0,0.0,pinetreefordlincoln,pinetreeford.com,1FTEW1EP1KFC68443,Ford,F-150,2019.0,NEW,Truck,403693.0,NaN,NaN,NaN,482898280a0e0ae76102926953ed4752,K1709,NaN,2019-08-03 22:10:38.805,2019-10-31 03:44:28.565
1,67421021.0,0.0,walkerjonescdjcllc,walkerjoneschryslerjeepdodge.com,3C6TRVCG4JE157071,Ram,ProMaster 2500,2018.0,NaN,Cargo Van,NaN,NaN,NaN,11.0,NaN,403126,NaN,2019-08-06 15:37:39.681,2019-10-26 17:37:48.420
2,68834621.0,0.0,evansvillemercedesmb,evansvillemercedes.com,WDC0G8EB0LF687867,Mercedes-Benz,GLC 300,2020.0,NEW,SUV,407735.0,NaN,NaN,NaN,d81ac0ea0a0e0adf1c4ee09c99597ede,53545,NaN,2019-08-30 10:51:54.583,2019-10-28 08:59:16.679
3,69421969.0,0.0,mileasubarusoa,mileasubaru.com,JF1VA1A6XL9801603,Subaru,WRX,2020.0,NaN,Sedan,NaN,21.0,27.0,NaN,NaN,NaN,NaN,2019-09-19 09:50:41.499,2019-10-31 16:45:43.539
4,574405.0,0.0,plazalexus,plazalexus.com,WDC0G4KB7HF258245,Mercedes-Benz,GLC,2017.0,USED,SUV,388307.0,NaN,NaN,NaN,9d5234ba0a0e0adf0d8014510e0a97b7,HF258245,NaN,2019-08-17 06:42:34.607,2019-10-13 11:24:13.753

In [11]:
ddc_listings['svoc_id'] = ddc_listings['svoc_id'].astype(int)
ddc_listings['svoc_id'] = ddc_listings['svoc_id'].astype(str)

In [12]:
ddc_match = client_master.loc[:,['acctnum','caid']]

In [13]:
ddc_match = pd.merge(ddc_listings, ddc_match.drop_duplicates(subset=['acctnum']), left_on='svoc_id', right_on='acctnum',how='left')

In [14]:
ddc_match.head()

,svoc_id,isFD,dealercode,domain,vin,vehiclemake,vehiclemodel,vehiclemodelyear,vehicletypestring,vehiclebodystyle,...,mpgcity,mpghighway,odometermiles,vehicleid,vehiclestocknumber,price,first_seen_datetime,last_seen_datetime,acctnum,caid
0,70705895,0.0,pinetreefordlincoln,pinetreeford.com,1FTEW1EP1KFC68443,Ford,F-150,2019.0,NEW,Truck,...,NaN,NaN,NaN,482898280a0e0ae76102926953ed4752,K1709,NaN,2019-08-03 22:10:38.805,2019-10-31 03:44:28.565,70705895,CA11268723
1,67421021,0.0,walkerjonescdjcllc,walkerjoneschryslerjeepdodge.com,3C6TRVCG4JE157071,Ram,ProMaster 2500,2018.0,NaN,Cargo Van,...,NaN,NaN,11.0,NaN,403126,NaN,2019-08-06 15:37:39.681,2019-10-26 17:37:48.420,67421021,CA11242269
2,68834621,0.0,evansvillemercedesmb,evansvillemercedes.com,WDC0G8EB0LF687867,Mercedes-Benz,GLC 300,2020.0,NEW,SUV,...,NaN,NaN,NaN,d81ac0ea0a0e0adf1c4ee09c99597ede,53545,NaN,2019-08-30 10:51:54.583,2019-10-28 08:59:16.679,NaN,NaN
3,69421969,0.0,mileasubarusoa,mileasubaru.com,JF1VA1A6XL9801603,Subaru,WRX,2020.0,NaN,Sedan,...,21.0,27.0,NaN,NaN,NaN,NaN,2019-09-19 09:50:41.499,2019-10-31 16:45:43.539,69421969,CA11253260
4,574405,0.0,plazalexus,plazalexus.com,WDC0G4KB7HF258245,Mercedes-Benz,GLC,2017.0,USED,SUV,...,NaN,NaN,NaN,9d5234ba0a0e0adf0d8014510e0a97b7,HF258245,NaN,2019-08-17 06:42:34.607,2019-10-13 11:24:13.753,574405,CA11220619

In [15]:
ddc_match.shape

(6057530, 21)

In [16]:
b = vma[vma['Source']=='ddc_listi']

In [18]:
a = ddc_match.loc[:,['caid']]
c = ddc_match.loc[:,['price','svoc_id']]

In [26]:
a.shape

(6057530, 1)

In [38]:
b = b.iloc[:,2:23]

In [39]:
b.shape

(6057530, 21)

In [28]:
c.shape

(6057530, 2)

In [45]:
a.reset_index(drop=True, inplace=True)
b.reset_index(drop=True, inplace=True)
c.reset_index(drop=True, inplace=True)

In [46]:
ddc_321 = pd.concat([a,b,c], axis=1,ignore_index=False)

In [47]:
ddc_321.shape

(6057530, 24)

In [51]:
ddc_321 = ddc_321.sort_values(by=['caid'])

In [52]:
ddc_321.head()

,caid,Vin,Year,Make,Model,Trim,Mileage,Date,MIDMapAlgorithm,mid15,VPID,MMR_adj_current,RMI_adj_current,AvgPrice,avgmiles,Velocity,Salesefficiency,AvgDaysToSell,vol_tier,availability,inventory,spread_current,price,svoc_id
4200630,CA11197380,5NPE34AF5GH274704,2016,Hyundai,Sonata,Sedan,19310.0,2019-10-20,Exact,2.016059e+14,2016_Hyundai_Sonata,16000.0,17550.0,11112.0,44270.0,Cold,0.693079,21.0,Tier1,Low,502.0,1550.0,NaN,100022386
2909399,CA11197380,2HGFB6E50DH705377,2013,Honda,Civic,Other,NaN,2019-10-12,Exact,2.013023e+14,2013_Honda_Civic Sdn,10150.0,13900.0,7138.0,92944.0,Hot,0.685657,19.0,Tier2,Medium,140.0,3750.0,NaN,100022386
5812067,CA11197380,1GTR2VE7XCZ218323,2012,GMC,Sierra 1500,Truck,NaN,2019-10-30,Exact,2.012022e+14,2012_GMC_Sierra 1500,11750.0,16600.0,13051.0,116676.0,Warm,0.494258,15.0,Tier3,Medium,61.0,4850.0,NaN,100022386
1332437,CA11197387,WP0CB2A84KS228839,2019,Porsche,718 Boxster,Cabriolet,4.0,2019-10-30,Popular,2.019045e+14,2019_Porsche_718 Boxster,NaN,NaN,66853.0,4327.0,Hot,0.743243,29.0,Tier5,High,13.0,NaN,NaN,100009062
5726040,CA11197387,WP1AG2A52HLB50755,2017,Porsche,Macan,SUV,23265.0,2019-10-31,Exact,2.017045e+14,2017_Porsche_Macan,49200.0,55200.0,37936.0,32310.0,Hot,0.656190,20.0,Tier3,High,117.0,6000.0,NaN,100009062

In [53]:
ddc_321.to_csv('ddc_321.csv')

In [54]:
del ddc_321
del a
del b
del c
del ddc_match

In [56]:
atc_listings = pd.read_csv('atc_listings.csv')

In [62]:
atc_match = client_master.loc[:,['acctnum','caid']]

In [61]:
atc_match.head()

     acctnum        caid
31    607305  CA11227024
56  70932111  CA11759037
59  68207825  CA11245678
72  66977397  CA11242463
85  70548051  CA11265118

In [64]:
atc_listings['CUSTOMER_ID'] = atc_listings['CUSTOMER_ID'].astype(int)
atc_listings['CUSTOMER_ID'] = atc_listings['CUSTOMER_ID'].astype(str)

In [65]:
atc_match = pd.merge(atc_listings, atc_match.drop_duplicates(subset=['acctnum']), left_on='CUSTOMER_ID', right_on='acctnum',how='left')

In [66]:
atc_match.head()

,CAR_ID,CUSTOMER_ID,STOCK_ID,VIN,MAKE,MODEL,MODEL_YEAR,TRIM_NAME,BODYSTYLE,NEW_IND,CERTIFIED_IND,PRICE_NUM,MSRP_NUM,MILEAGE_NUM,SPOTLIGHT_IND,REDUCED_IND,SPECIAL_CNT,INCENTIVE_PRICE,PAYMENT_OFFERS_IND,MAIN_LISTING_IMAGE_URL,SOURCE_CREATED_DATETIME,SOURCE_MODIFIED_DATETIME,DELETE_RECORD_IND,OEM_COLOR,COLOR,INT_COLOR,DOORS,ENGINE_TYPE,FUEL_TYPE,DRIVE_TYPE,TRANSMISSION_TYPE,acctnum,caid
0,485750148,70042,P25088,1LN6L9RP0J5606615,Lincoln,Continental,2018,Reserve,Sedan,0,1,60935,0,5182,0,0,0,0,0,https://dealers-admin.autotrader.com/dc/images...,2019-08-07,2019-08-27,1,WHITE PLATINUM METALLIC TRI-CO,WHITE,BROWN,Four Door,6-Cylinder Turbo,Gasoline,2 Wheel Drive - Front,AUTOMATIC,70042,CA11258738
1,492720575,83813,37230,JTJYARBZXK2125964,Lexus,NX 300,2019,FWD,Sport Utility,1,0,40133,44733,30,0,0,0,0,0,https://dealers-admin.autotrader.com/dc/images...,2019-09-17,2019-09-30,1,CAVIAR,UNAVAIL,OFFWHITE,Four Door,4-Cylinder Turbo,Gasoline,2 Wheel Drive - Front,AUTOMATIC,83813,CA11349128
2,472773630,67878603,P2510,JN1BJ1CP3HW025765,Nissan,Rogue Sport,2017,SL,Sport Utility,0,0,22995,0,8,0,0,0,0,0,https://dealers-admin.autotrader.com/dc/images...,2019-08-23,2019-09-05,1,MAGNETIC BLACK,BLACK,CHARCOAL,Four Door,4-Cylinder,Gasoline,2 Wheel Drive - Front,AUTOMATIC,67878603,CA11245617
3,472773630,72394791,P2510,JN1BJ1CP3HW025765,Nissan,Rogue Sport,2017,SL,Sport Utility,0,1,20700,0,8,0,0,0,0,0,https://dealers-admin.autotrader.com/dc/images...,2019-08-23,2019-12-27,1,MAGNETIC BLACK,BLACK,CHARCOAL,Four Door,4-Cylinder,Gasoline,2 Wheel Drive - Front,AUTOMATIC,NaN,NaN
4,483058027,1359774,18-722,WMWXM5C5XF3A04636,MINI,Cooper,2015,2-Door Hardtop,Hatchback,0,0,12990,0,18156,0,0,0,0,0,https://dealers-admin.autotrader.com/dc/images...,2019-10-29,2019-10-29,1,GREEN,GREEN,BLACK,Two Door,3-Cylinder Turbo,Gasoline,2 Wheel Drive - Front,MANUAL,1359774,CA11204586

In [68]:
b = vma[vma['Source']=='atc_listi']
b = b.iloc[:,2:23]

In [69]:
b.shape

(9215447, 21)

In [71]:
del vma

In [73]:
del atc_listings

In [75]:
a = atc_match.loc[:,['caid']]
c = atc_match.loc[:,['PRICE_NUM','CUSTOMER_ID']]

In [76]:
a.shape

(9215447, 1)

In [77]:
c.shape

(9215447, 2)

In [78]:
a.reset_index(drop=True, inplace=True)
b.reset_index(drop=True, inplace=True)
c.reset_index(drop=True, inplace=True)

In [79]:
atc_321 = pd.concat([a,b,c], axis=1,ignore_index=False)

In [80]:
atc_321.shape

(9215447, 24)

In [81]:
atc_321 = atc_321.sort_values(by=['caid'])

In [1]:
atc_321.head()

NameError: name 'atc_321' is not defined

In [ ]:
atc_321.to_csv('atc_321.csv')

In [3]:
atc_321 = pd.read_csv('atc_321.csv')

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
atc_321.isna().sum()

Unnamed: 0               0
caid               2226067
Vin                     29
Year                     0
Make                     0
Model                    0
Trim                     0
Mileage                  0
Date                     0
MIDMapAlgorithm          0
mid15                20339
VPID                 62405
MMR_adj_current    1400670
RMI_adj_current    1178222
AvgPrice            429366
avgmiles            429366
Velocity            649661
Salesefficiency     429452
AvgDaysToSell       429366
vol_tier            429366
availability        429367
inventory           453748
spread_current     1742968
PRICE_NUM                0
CUSTOMER_ID              0
dtype: int64

In [6]:
atc_321.columns

Index(['Unnamed: 0', 'caid', 'Vin', 'Year', 'Make', 'Model', 'Trim', 'Mileage',
       'Date', 'MIDMapAlgorithm', 'mid15', 'VPID', 'MMR_adj_current',
       'RMI_adj_current', 'AvgPrice', 'avgmiles', 'Velocity',
       'Salesefficiency', 'AvgDaysToSell', 'vol_tier', 'availability',
       'inventory', 'spread_current', 'PRICE_NUM', 'CUSTOMER_ID'],
      dtype='object')